name: Run Python Script

on:
  schedule:
    - cron: '0 0 * * *'  # This cro n expression runs the job at midnight UTC every day
  push:
    branches:
      - main  # Run on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure you have a requirements.txt file in your repo

    - name: Debug environment
      run: |
        python --version
        pip --version
        pip list

    - name: Run script
      run: |
        python -u blogautomated.py  # Replace with the path to your Python script
